services:
  - type: web
    name: jamoveo
    env: node
    rootDir: server
    buildCommand: npm run build-client
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
